version: '3.9'

services:
  php:
    build: 
      context: .
      dockerfile: ./build/php/Dockerfile
      target: php
    container_name: "php-first-app"
    environment:
      DATABASE_URL: mysql:/$DB_USER:$DB_PASS@$DB_HOST:3306/db_name
    #volumes:
    #  - .:/var/www
    networks:
      - default


  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: "nginx-first-app"
  #   networks:
  #     - default
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./app/public:/var/www/app/public:ro
  #     - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  nginx:
    build: 
      context: .
      dockerfile: ./build/php/Dockerfile
      target: nginx
    container_name: "nginx-first-app"
    networks:
      - default
    ports:
      - 8080:80
    #volumes:
      #- ./app/public:/var/www/app/public:ro
      #- ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:

